#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

if [ -f /etc/init.d/apache2 ]; then
	/etc/init.d/apache2 start
else
	echo "You don't have apache installed!"
fi

if [ -f lib/admin/OpenVPNService.py ]; then
	python lib/admin/OpenVPNService.py &
else
	echo "You don't seem to have the OpenVPNService installed... try reinstalling"
fi
